CREATE TABLE IF NOT EXISTS ebooks (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  titulo VARCHAR(255) NOT NULL,
  descricao TEXT,
  arquivo LONGBLOB,
  arquivo_nome VARCHAR(255),
  arquivo_tamanho INT UNSIGNED,
  imagem_capa MEDIUMBLOB,
  ativo TINYINT(1) NOT NULL DEFAULT 1,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  atualizado_em DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS ebook_downloads (
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  ebook_id INT UNSIGNED NOT NULL,
  nome VARCHAR(150) NOT NULL,
  email VARCHAR(254) NOT NULL,
  inscrito_newsletter TINYINT(1) DEFAULT 0,
  criado_em DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_ebook (ebook_id),
  FOREIGN KEY (ebook_id) REFERENCES ebooks(id) ON DELETE CASCADE
) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
